<?php 
function tpl_4d45c0de_Text__yTlGJ1bKRVc50PNjARqkYQ(PHPTAL $tpl, PHPTAL_Context $ctx) {
$_thistpl = $tpl ;
$_translator = $tpl->getTranslator() ;
/* tag "documentElement" from line 1 */ ;
/* tag "mobi:page" from line 1 */ ;
?>
<mobi:page xmlns:mobi="http://mobility.pozitim.com">
	<?php /* tag "mobi:block" from line 2 */; ?>
<mobi:block>
		<?php /* tag "span" from line 3 */; ?>
<?php echo phptal_escape($ctx->only_phptal); ?>

		<?php echo $only_php; ?> - {$only_smarty} - {literal}{{ only_twig }}{/literal}
	</mobi:block>
</mobi:page><?php 
/* end */ ;

}

?>
<?php /* 
*** DO NOT EDIT THIS FILE ***

Generated by PHPTAL from /data/projects/personal/mvc/Application/View/Index/Text.php (edit that file instead) */; ?>